### ISSUE TITLE
REG: Firebase Access timeout when trying to access

### ISSUE THREAD

**Issue by Sureshee** [MGItkin/FreeRTOS-distributed-monitoring#1]
Hi,
 I'm trying to connect to the Firebase from Alexa, exactly similar to your concept for reading the snapshot data from Firebase once.  When i tried to query a data from the database, connection with firebase  always gets a timeout(service expired) based on the configuration parameter in Lambda function. Since it was a async access, I also tried adding a callback method to indicate the user when ALEXA receives a response, but it didn't work. Did you faced anything like this, during your development? Is there anything i could learn from your experience on this. Looking forward to hear from you soon.
Thanks 
Suresh

**Comment by MGItkin** [comment]
It sounds like you might be sending the response in Lambda before receiving the callback from firebase. Make sure that you call`this.emit()` after you have completed the callback or resolved the promise from firebase. If thats not it, there isn't much help I can give you without seeing your code.
